*** empty log message ***

diff --git a/MAKEDEV b/MAKEDEV
--- a/MAKEDEV
+++ b/MAKEDEV
@@ -1,6 +1,7 @@
 #! /bin/sh -
 
-# $Id: MAKEDEV,v 1.4 1994/03/14 17:07:49 alfie Exp alfie $
+RCSID='$Id: MAKEDEV,v 2.0 1994/07/17 20:41:37 alfie Exp alfie $'
+
 #---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#
 # Customisation:
 #   The devices fall into various classes.  This section contains the mapping
@@ -10,6 +11,7 @@
 # lines _must_ be of the format "user group perm".
 
  public="  root system 666"
+ system="  root system 660"
    kmem="  root kmem   660"
     tty="  root tty    666"
    cons="  root tty    622"	# 622 for console?
@@ -26,77 +28,8 @@ printer="  root daemon 660"
 scanner="  root system 666"
 
 #---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#
-#
-# This is my attempt at a MAKEDEV script.  IMHO it cleans up many areas.
-# It can be used to determine the necessary info for a device without
-# actually creating it using the '-n' flag.
-#
-# It makes less individual devices and tends to make classes of devices
-# (eg "MAKEDEV hda" will create "hda" and the 8 partitions; "MAKEDEV ptyp"
-# will create the ptyp[0-f] master and ttyp[0-f] slave devices).
-#
-# If you are aware of any glaring omissions or errors, please let me know.
-# Also, if you are a developer who wants your devices supported by MAKEDEV,
-# let me know.
-#
-# Thanks to Ian Jackson for the original help and encouragement.
-# 
-# 	Nick Holloway <Nick.Holloway@alfie.demon.co.uk>  
-#					Last changed: 17th July 1994
-# 
-#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#
-# Device 'make' file.  Valid arguments:
-# 
-#	generic		create a generic subset of devices
-#	local		configuration specific devices (runs MAKEDEV.local)
-#	std		standard devices
-#	update		create and delete devices based on current devices
-#			registered in running kernel
-#  Virtual Terminals:
-#	console		(also known as tty0)
-#	tty{0..63}	virtual consoles
-#  Serial devices:
-#	ttyS{0..63}	serial ports and corresponding dialout device
-#  Pseudo Terminals:
-#	pty[p-s]	banks of of master and slave pseudo terminals
-#  Parallel ports:
-#	par[0-3]	parallel ports
-#	lp[0-3]		   ""     ""
-#  Bus Mice:
-#	busmice		various bus mice
-#  Joystick:
-#	js		joystick
-#  Disks:
-#	fd[0-4]		floppy disks
-#	hd[a-d]		AT hard disks (1st controller)
-#	hd1[a-d]	2nd AT controller hard disks
-#	xd[a-d] 	XT hard disks
-#	sd[a-i]		SCSI hard disks
-#	loop		Loopback disk devices
-#  Tapes:
-#	st[0-1]		SCSI tapes
-#	qic		QIC-80 tapes
-#	ftape		floppy driver tapes (QIC-117)
-#  CD:
-#	scd[0-1]	SCSI CD players
-#	sonycd		Sony CDU-31A CD player
-#	mcd		Mitsumi CD player
-#	cdu535		Sony CDU-535 CD player
-#	lmscd		LMS/Philips CD player	(needs new major number)
-#	sbpcd		Sound Blaster CD player
-#	idecd		NEC CDR-260
-#  Scanner:
-#	scan		Logitech ScanMan32 & ScanMan 256
-#  Audio:
-#	audio		various audio devices
-#	pcaudio		audio devices used by pcsndrv
-#  Misc:
-#       sg		generic SCSI devices
-#	fd		file names for file descriptors
-#	ibcs2		devices (and symlinks) needed by ibcs2 emulation
-#	helloworld	module demonstration device
-#
-#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#
+
+procfs=/proc
 
 opt_v=
 opt_d=
@@ -109,30 +42,44 @@ do
 		-v)	shift; opt_v=1 ;;
 		-d)	shift; opt_d=1 ;;
 		-n)	shift; opt_n=1; opt_v=1 ;;
+		-V)	shift; opt_V=1 ;;
 		-*)	echo "$0: unknown flag \"$1\"" >&2; exit 1 ;;
 		*)	break ;;
 	esac
 done
+
+if [ "$opt_V" ]
+then
+	echo "$RCSID"
+	exit 0
+fi
 
 opts="${opt_n:+-n} ${opt_v:+-v} ${opt_d:+-d}"
 
 makedev () {	# usage: makedev name [bcu] major minor owner group mode
 	if [ "$opt_v" ]
 	then	if [ "$opt_d" ]
-		then	echo "rm -f $1"
-		else	echo "$1	= $2 $3 $4 $5:$6 $7" 
+		then	echo "delete $1"
+		else	echo "create $1	$2 $3 $4 $5:$6 $7" 
 		fi
 	fi
-	[ ! "$opt_n" ] && rm -f $1 &&
-	[ ! "$opt_d" ] && mknod $1 $2 $3 $4 &&
-		chown $5:$6 $1 &&
-		chmod $7 $1
+	if [ ! "$opt_n" ]
+	then	if [ "$opt_d" ]
+		then
+			rm -f $1
+		else
+			mknod $1- $2 $3 $4 &&
+			chown $5:$6 $1- &&
+			chmod $7 $1- &&
+			mv $1- $1
+		fi
+	fi
 }
 symlink () {	# usage: symlink name target
 	if [ "$opt_v" ]
 	then	if [ "$opt_d" ]
-		then	echo "rm -f $1"
-		else	echo "$1	-> $2"
+		then	echo "delete $1"
+		else	echo "create $1	-> $2"
 		fi
 	fi
 	[ ! "$opt_n" ] && rm -f $1 &&
@@ -140,11 +87,11 @@ symlink () {	# usage: symlink name target
 }
 
 devices=
-if [ ! -f /proc/devices ]
+if [ ! -f $procfs/devices ]
 then
-	echo "$0: warning: can't read /proc/devices" >&2
+	echo "$0: warning: can't read $procfs/devices" >&2
 else
-	exec 3</proc/devices
+	exec 3<$procfs/devices
 	while read major device <&3
 	do
 		case "$major" in
@@ -163,7 +110,7 @@ Major () {
 	device=$2
 	if [ "$opt_d" ]
 	then
-		echo -1
+		echo -1	# don't care
 	else
 		eval echo \${major_$1:-\${device:?\"unknown major number for $1\"}}
 	fi
@@ -173,19 +120,26 @@ cvt () {
 	while [ $# -ne 0 ]
 	do
 		case "$1" in
-			mem|tty)	;;
+			mem|tty|ttyp|cua|cub)	;;
 			hd)	echo hda hdb ;;
 			xd)	echo xda xdb ;;
 			fd)	echo fd0 fd1 ;;
 			lp)	echo lp0 lp1 lp2 ;;
 			mt)	echo ftape ;;
-			lo)	echo loop ;;
+			loop)	echo loop ;;
 			ibcs2)	echo ibcs2 ;;
 			tpqic02)	echo qic ;;
 			sound)		echo audio ;;
-			Scanner)	echo scan ;;
+			logiscan)	echo logiscan ;;
+			ac4096)		echo ac4096 ;;
 			idecd)	echo idecd ;;
 			hw)	echo helloworld ;;
+			sbpcd | sbpcd[123])	echo $1 ;;
+			Joystick)	echo js ;;
+			apm_bios)	echo apm ;;
+			dcf)		echo dcf ;;
+			pcmcia)	;; # taken care of by its own driver
+			ttyC)	echo cyclades ;;
 			*)	echo "$0: don't know what \"$1\" is" >&2 ;;
 		esac
 		shift
@@ -218,7 +172,7 @@ do
 		makedev null c 1 3 $public
 		makedev port c 1 4 $kmem
 		makedev zero c 1 5 $public
-		symlink core /proc/kcore
+		symlink core $procfs/kcore
 		makedev full c 1 7 $public
 		makedev ram  b 1 1 $disk
 		makedev tty  c 5 0 $tty
@@ -247,6 +201,15 @@ do
 			makedev tty$bank$i c 4 `expr 192 + $base + $j` $tty
 		done
 		;;
+	cyclades)
+		major1=`Major ttyC` || continue
+		major2=`Major cub` || continue
+		for i in 0 1 2 3 4 5 6 7 # 8 9 10 11 12 13 14 15
+		do
+			makedev ttyC$i c $major1 `expr 32 + $i` $tty
+			makedev cub$i c $major2 `expr 32 + $i` $dialout
+		done
+		;;
 	par[0-2])
 		major=`Major lp 6` || continue
 		port=`expr $arg : "par\(.\)"`
@@ -263,32 +226,48 @@ do
 		makedev psaux    c $major 1 $mouse
 		makedev inportbm c $major 2 $mouse
 		makedev atibm    c $major 3 $mouse
+		# makedev sejin    c $major 4 $mouse
 		;;
 	js)
-		makedev js0 c 15 0 $mouse
-		makedev js1 c 15 1 $mouse
+		major=`Major Joystick` || continue
+		makedev js0 c $major 0 $mouse
+		makedev js1 c $major 1 $mouse
 		;;
 	fd[0-4])
+		major=`Major fd 2` || continue
 		unit=`expr $arg : "fd\(.\)"`
-		makedev fd${unit} b 2 $unit $floppy
-		makedev fd${unit}d360  b 2 `expr $unit +  4` $floppy
-		makedev fd${unit}h1200 b 2 `expr $unit +  8` $floppy
-		makedev fd${unit}D360  b 2 `expr $unit + 12` $floppy
-		makedev fd${unit}H360  b 2 `expr $unit + 12` $floppy
-		makedev fd${unit}D720  b 2 `expr $unit + 16` $floppy
-		makedev fd${unit}H720  b 2 `expr $unit + 16` $floppy
-		makedev fd${unit}h360  b 2 `expr $unit + 20` $floppy
-		makedev fd${unit}h720  b 2 `expr $unit + 24` $floppy
-		makedev fd${unit}H1440 b 2 `expr $unit + 28` $floppy
-		makedev fd${unit}H2880 b 2 `expr $unit + 32` $floppy
+		makedev fd${unit} b $major $unit $floppy
+		makedev fd${unit}d360  b $major `expr $unit +  4` $floppy
+		makedev fd${unit}h1200 b $major `expr $unit +  8` $floppy
+		makedev fd${unit}D360  b $major `expr $unit + 12` $floppy
+		symlink fd${unit}H360 fd${unit}D360
+		makedev fd${unit}D720  b $major `expr $unit + 16` $floppy
+		symlink fd${unit}H720 fd${unit}D720
+		makedev fd${unit}h360  b $major `expr $unit + 20` $floppy
+		makedev fd${unit}h720  b $major `expr $unit + 24` $floppy
+		makedev fd${unit}H1440 b $major `expr $unit + 28` $floppy
+		makedev fd${unit}E2880 b $major `expr $unit + 32` $floppy
+		makedev fd${unit}CompaQ b $major `expr $unit + 36` $floppy
+
+		makedev fd${unit}h1440 b $major `expr $unit + 40` $floppy
+		makedev fd${unit}H1680 b $major `expr $unit + 44` $floppy
+		makedev fd${unit}h410  b $major `expr $unit + 48` $floppy
+		makedev fd${unit}H820  b $major `expr $unit + 52` $floppy
+		makedev fd${unit}h1476 b $major `expr $unit + 56` $floppy
+		makedev fd${unit}H1722 b $major `expr $unit + 60` $floppy
+		makedev fd${unit}h420  b $major `expr $unit + 64` $floppy
+		makedev fd${unit}H830  b $major `expr $unit + 68` $floppy
+		makedev fd${unit}h1494 b $major `expr $unit + 72` $floppy
+		makedev fd${unit}H1743 b $major `expr $unit + 76` $floppy
 		;;
 	hd[a-d])
+		major=`Major hd 3` || continue
 		unit=`expr $arg : "hd\(.\)"`
 		base=`expr \( abcd : ".*$unit" - 1 \) \* 64`
-		makedev hd$unit b 3 $base $disk
+		makedev hd$unit b $major $base $disk
 		for part in 1 2 3 4 5 6 7 8 # 9 10 11 12 13 14 15 16
 		do
-			makedev hd$unit$part b 3 `expr $base + $part` $disk
+			makedev hd$unit$part b $major `expr $base + $part` $disk
 		done
 		;;
 	hd1[a-d])
@@ -322,13 +301,13 @@ do
 		done
 		;;
 	loop)
-		major=`Major lo` || continue
+		major=`Major loop` || continue
 		for part in 0 1 2 3 4 5 6 7
 		do
 			makedev loop$part b $major $part $disk
 		done
 		;;
-	st[0-1])
+	st[0-7])
 		major=`Major st 9`
 		unit=`expr $arg : "st\(.\)"`
 		makedev st$unit c $major $unit $tape
@@ -351,13 +330,13 @@ do
 		symlink ftape rft0
 		symlink nftape nrft0
 		;;
-	scd[0-1])
+	scd[0-7])
 		major=`Major sr 11` || continue
 		unit=`expr $arg : "scd\(.\)"`
 		makedev scd$unit b $major $unit $cdrom
 		;;
 	sonycd)
-		major=`Major cdu31a 15` || continue
+		major=`Major cdu31a` || continue
 		makedev $arg b $major 0 $cdrom
 		;;
 	mcd)
@@ -370,35 +349,55 @@ do
 	lmscd)
 		makedev $arg b 24 0 $cdrom
 		;;
-	sbpcd)
-		major=`Major sbpcd 25` || continue
-		makedev $arg    b $major 0 $cdrom
-		makedev ${arg}0 b $major 0 $cdrom
-		makedev ${arg}1 b $major 1 $cdrom
-		makedev ${arg}2 b $major 2 $cdrom
-		makedev ${arg}3 b $major 3 $cdrom
+	sbpcd|sbpcd[123])
+		major=`Major $arg` || continue
+		base=`expr ${arg}0 : "sbpcd\(.\)"`
+		for minor in 0 1 2 3
+		do
+			unit=`expr substr 0123456789abcdef \( $base \* 4 + $minor + 1 \) 1`
+			makedev spbcd$unit b $major $minor $cdrom
+		done
+		[ $arg = sbpcd ] && symlink $arg ${arg}0
 		;;
-	scan)
-		major=`Major Scanner` || continue;
-		makedev $arg    c $major 0 $scanner
-#		makedev ${arg}d c $major 1 $scanner
+	idecd)
+		major=`Major idecd` || continue
+		makedev $arg c $major 0 $cdrom
+		;;
+	logiscan)
+		major=`Major logiscan` || continue
+		makedev $arg c $major 0 $scanner
+		;;
+	m105scan)
+		major=`Major m105` || continue
+		makedev $arg c $major 0 $scanner
+		;;
+	ac4096)
+		major=`Major ac4096` || continue
+		makedev $arg c $major 0 $scanner
 		;;
 	audio)
 		major=`Major sound 14`
-		makedev mixer     c $major 0 $audio
-		makedev sequencer c $major 1 $audio
-		makedev midi      c $major 2 $audio
-		makedev dsp       c $major 3 $audio
-		makedev audio     c $major 4 $audio
-		makedev sndstat   c $major 6 $audio
-		makedev mixer1    c $major 16 $audio
-		makedev dsp1      c $major 19 $audio
-		makedev audio1    c $major 20 $audio
+		makedev mixer      c $major  0 $audio
+		makedev sequencer  c $major  1 $audio
+		makedev midi00     c $major  2 $audio
+		makedev dsp        c $major  3 $audio
+		makedev audio      c $major  4 $audio
+		makedev sndstat    c $major  6 $audio
+#		makedev sequencer2 c $major  8 $audio
+		makedev mixer1     c $major 16 $audio
+#		makedev patmgr0    c $major 17 $audio
+		makedev midi01     c $major 18 $audio
+		makedev dsp1       c $major 19 $audio
+		makedev audio1     c $major 20 $audio
+#		makedev patmgr1    c $major 33 $audio
+		makedev midi02     c $major 34 $audio
+		makedev midi03     c $major 50 $audio
 		;;
 	pcaudio)
-		makedev pcmixer c 30 0 $audio
-		makedev pcsp    c 30 3 $audio
-		makedev pcaudio c 30 4 $audio
+		major=`Major pcsp` || continue
+		makedev pcmixer c $major 0 $audio
+		makedev pcsp    c $major 3 $audio
+		makedev pcaudio c $major 4 $audio
 		;;
 	sg)
 		major=`Major sg 21`
@@ -410,16 +409,25 @@ do
 		;;
 	fd)
 		# not really devices, we use the /proc filesystem
-		symlink fd     /proc/self/fd
+		symlink fd     $procfs/self/fd
 		symlink stdin  fd/0
 		symlink stdout fd/1
 		symlink stderr fd/2
 		;;
 	ibcs2)
-		major=`Major ibcs2 30` || continue
+		major=`Major ibcs2` || continue
 		makedev socksys c $major 0 $ibcs2
+		symlink nfsd socksys
 		makedev spx     c $major 1 $ibcs2
-		symlink XOR null
+		symlink X0R null
+		;;
+	apm)
+		major=`Major apm_bios` || continue
+		makedev $arg c $major 0 $system
+		;;
+	dcf)
+		major=`Major dcf` || continue
+		makedev $arg c $major 0 $system
 		;;
 	helloworld)
 		major=`Major hw` || continue
